
export * as drag_indicator from '@material-symbols/svg-400/outlined/drag_indicator.svg?component'
export * as close from '@material-symbols/svg-400/outlined/close.svg?component'
export * as arrow_back from '@material-symbols/svg-400/outlined/arrow_back.svg?component'
export * as arrow_forward from '@material-symbols/svg-400/outlined/arrow_forward.svg?component'
export * as copyright from '@material-symbols/svg-400/outlined/copyright.svg?component'
export * as auto_stories from '@material-symbols/svg-400/outlined/auto_stories.svg?component'
export * as subject from '@material-symbols/svg-400/outlined/subject.svg?component'
export * as download from '@material-symbols/svg-400/outlined/download.svg?component'
export * as error from '@material-symbols/svg-400/outlined/error.svg?component'
export * as help from '@material-symbols/svg-400/outlined/help.svg?component'
export * as currency_bitcoin from
'@material-symbols/svg-400/outlined/currency_bitcoin.svg?component'
export * as credit_card from '@material-symbols/svg-400/outlined/credit_card.svg?component'
export * as account_balance from '@material-symbols/svg-400/outlined/account_balance.svg?component'
export * as check from '@material-symbols/svg-400/outlined/check.svg?component'
export * as expand_circle_up from
'@material-symbols/svg-400/outlined/expand_circle_up.svg?component'
export * as paid from '@material-symbols/svg-400/outlined/paid.svg?component'
export * as step_out from '@material-symbols/svg-400/outlined/step_out.svg?component'
export * as stacks from '@material-symbols/svg-400/outlined/stacks.svg?component'
export * as emoji_people from '@material-symbols/svg-400/outlined/emoji_people.svg?component'
export * as equalizer from '@material-symbols/svg-400/outlined/equalizer.svg?component'
export * as world from '@material-symbols/svg-400/outlined/public.svg?component'
export * as more_vert from '@material-symbols/svg-400/outlined/more_vert.svg?component'
export * as menu from '@material-symbols/svg-400/outlined/menu.svg?component'
export * as mail from '@material-symbols/svg-400/outlined/mail.svg?component'
export * as send_money from '@material-symbols/svg-400/outlined/send_money.svg?component'
export * as thumb_up from '@material-symbols/svg-400/outlined/thumb_up.svg?component'
export * as link from '@material-symbols/svg-400/outlined/link.svg?component'

export * as facebook from '@/assets/icons/facebook.svg?component'
